name: firestore_todos_api
description: My new Firestore package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.4.3
  fake_cloud_firestore: ^3.0.3
  flutter:
    sdk: flutter
  todos_api:
    path: ../todos_api
 
dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
